# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 714f96692785d01d879106558ad1f304b477584880c9f13359b446f35732255fb04c8e4c78364749ea8da950c037c8c407cef4cfa6c99cd373021489737cabbe

test:
  secret_key_base: 2576ae253c9088ec07a258e54940ad6c4ffac5559648ff1da48dba57f754b10e79438125bdc5ca973694a5f667bfd9d977e1d9a9521a4f2dd7634d6f31f94fa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
